name: Sample book application workflow

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
  deploy-dev:
    runs-on: "self-hosted"
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: ·/.github/actions/deploy
        with:
          environment: 'DEV'
          port: '1100'
  test-dev:
    runs-on: "self-hosted"
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'ZaliveVerty/api-automation.git'
          ref: 'main'
      - name: Print step name
        run: echo "Testing BOOKS test set on DEV has started..."
      - name: "Install all dependencies"
        run: npm install
      - name: Run API tests
        run: npm run BOOKS BOOKS_DEV
  deploy-stg:
    runs-on: "self-hosted"
    needs: [test-dev]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          environment: 'STG'
          port: '2200'
  test-stg:
    runs-on: "self-hosted"
    needs: [deploy-stg]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on STG has started..."
  deploy-prd:
    runs-on: "self-hosted"
    needs: [test-stg]
    steps:
      - uses: actions/checkout@v4
      - uses: ·/.github/actions/deploy
        with:
          environment: 'PRD'
          port: '3300'
  test-prd:
    runs-on: "self-hosted"
    needs: [deploy-prd]
    steps:
      - uses: actions/checkout@v4
      - name: Print step name
        run: echo "Testing BOOKS test set on PRD has started..."
